server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///chatroom?serverTimezone=GMT%2B8
    username: userName
    password: password
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  redis:
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    host: 47.98.149.186
    port: 6379
    database: 0
    timeout: 1800000
    password: Ww46288700

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:com/xunle/chatroom/mapper/xml/*.xml
  # 逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#阿里云oss
aliyun:
  oss:
    file:
      endPoint: oss-cn-beijing.aliyuncs.com
      #阿里云bucketId
      keyId: keyId
      #阿里云bucket密码
      keySecret: keySecret
      bucketName: xunle-chatroom
